#:schema node_modules/wrangler/config-schema.json
name = "bolt-welum"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"
send_metrics = false
compatibility_date = "2024-09-23"
